/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './rotas/__root'
import { Route as IndexRouteImport } from './rotas/index'
import { Route as ProtegidoRouteImport } from './rotas/_protegido'
import { Route as CadastroRouteImport } from './rotas/cadastro'
import { Route as EntradaRouteImport } from './rotas/entrada'
import { Route as ProtegidoAgendaRouteImport } from './rotas/_protegido/agenda'
import { Route as ProtegidoConfiguracoesRouteImport } from './rotas/_protegido/configuracoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtegidoRoute = ProtegidoRouteImport.update({
  id: '/_protegido',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradaRoute = EntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtegidoAgendaRoute = ProtegidoAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ProtegidoRoute,
} as any)
const ProtegidoConfiguracoesRoute = ProtegidoConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => ProtegidoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/entrada': typeof EntradaRoute
  '/agenda': typeof ProtegidoAgendaRoute
  '/configuracoes': typeof ProtegidoConfiguracoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/entrada': typeof EntradaRoute
  '/agenda': typeof ProtegidoAgendaRoute
  '/configuracoes': typeof ProtegidoConfiguracoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protegido': typeof ProtegidoRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/entrada': typeof EntradaRoute
  '/_protegido/agenda': typeof ProtegidoAgendaRoute
  '/_protegido/configuracoes': typeof ProtegidoConfiguracoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cadastro' | '/entrada' | '/agenda' | '/configuracoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cadastro' | '/entrada' | '/agenda' | '/configuracoes'
  id:
    | '__root__'
    | '/'
    | '/_protegido'
    | '/cadastro'
    | '/entrada'
    | '/_protegido/agenda'
    | '/_protegido/configuracoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtegidoRoute: typeof ProtegidoRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  EntradaRoute: typeof EntradaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protegido': {
      id: '/_protegido'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtegidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrada': {
      id: '/entrada'
      path: '/entrada'
      fullPath: '/entrada'
      preLoaderRoute: typeof EntradaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protegido/agenda': {
      id: '/_protegido/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof ProtegidoAgendaRouteImport
      parentRoute: typeof ProtegidoRoute
    }
    '/_protegido/configuracoes': {
      id: '/_protegido/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ProtegidoConfiguracoesRouteImport
      parentRoute: typeof ProtegidoRoute
    }
  }
}

interface ProtegidoRouteChildren {
  ProtegidoAgendaRoute: typeof ProtegidoAgendaRoute
  ProtegidoConfiguracoesRoute: typeof ProtegidoConfiguracoesRoute
}

const ProtegidoRouteChildren: ProtegidoRouteChildren = {
  ProtegidoAgendaRoute: ProtegidoAgendaRoute,
  ProtegidoConfiguracoesRoute: ProtegidoConfiguracoesRoute,
}

const ProtegidoRouteWithChildren = ProtegidoRoute._addFileChildren(
  ProtegidoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtegidoRoute: ProtegidoRouteWithChildren,
  CadastroRoute: CadastroRoute,
  EntradaRoute: EntradaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
